### ISSUE TITLE
[Core feature request] concurrency

### ISSUE THREAD

**Issue by jmfayard** [krzema12/github-actions-kotlin-dsl#119]
**What feature do you need?**

- https://docs.github.com/en/actions/using-jobs/using-concurrency
- https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idconcurrency

**Do you have an example usage?**

```yaml
concurrency: staging_environment
```

```yaml
concurrency: 
  group: ${{ github.ref }}
  cancel-in-progress: true
```

Keep in mind that it's available both
- at a workflow level
- at `jobs.<job_id>.concurrency` level
