### ISSUE TITLE
[Core feature request] type-safe expressions

### ISSUE THREAD

**Issue by jmfayard** [krzema12/github-actions-kotlin-dsl#203]
**What feature do you need?**

- [Functions](https://docs.github.com/en/actions/learn-github-actions/expressions#functions)
- [Default environment variables](https://docs.github.com/en/actions/learn-github-actions/environment-variables#default-environment-variables)
- [contexts](https://docs.github.com/en/actions/learn-github-actions/contexts)
- [Context availability](https://docs.github.com/en/actions/learn-github-actions/contexts#context-availability)
- [_Webhook events and payloads_](https://docs.github.com/-en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads)

**Do you have an example usage?**

https://docs.github.com/en/actions/learn-github-actions/contexts#example-printing-context-information-to-the-log

```yaml
name: Context testing
on: push

jobs:
  dump_contexts_to_log:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        id: github_context_step
        run: echo '${{ toJSON(github) }}'
      - name: Dump job context
        run: echo '${{ toJSON(job) }}'
      - name: Dump steps context
        run: echo '${{ toJSON(steps) }}'
      - name: Dump runner context
        run: echo '${{ toJSON(runner) }}'
      - name: Dump strategy context
        run: echo '${{ toJSON(strategy) }}'
      - name: Dump matrix context
        run: echo '${{ toJSON(matrix) }}'
``` 

**Experiment**

```yaml
github.token shouldBe "github.token"
event.pullRequest.commits shouldBe "event.pull_request.commits"
event.pullRequest.assignees[1] shouldBe "event.pull_request.assignees[1]"
```

See https://github.com/krzema12/github-actions-kotlin-dsl/pull/202
