### ISSUE TITLE
Implement using GitHub variables

### ISSUE THREAD

**Issue by krzema12** [krzema12/github-actions-kotlin-dsl#26]

**Comment by jmfayard** [comment]
That's the workflow:

```yaml
      - name: create-branch
        uses: peterjgrainger/action-create-branch@v2.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: dependency-update
```
