### ISSUE TITLE
[Core feature request] shell option for run steps

### ISSUE THREAD

**Issue by Vampire** [krzema12/github-actions-kotlin-dsl#286]
**What feature do you need?**
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsshell

**Do you have an example usage?**
```yaml
- shell: kotlin -howtorun .main.kts {0}
  run: |
     println("Hello World!")
```
```kts
run(
    shell = "kotlin -howtorun .main.kts {0}"
    // language=kotlin
    command = """
        println("Hello World!")
    """.trimIndent()
)
```
