### ISSUE TITLE
[Core feature request] continue-on-error for steps

### ISSUE THREAD

**Issue by Vampire** [krzema12/github-actions-kotlin-dsl#290]
**What feature do you need?**
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepscontinue-on-error

**Do you have an example usage?**
```yml
- id: "execute_action"
  uses: "./"
  with:
    "distribution": "${{ matrix.distribution.user-id }}"
  continue-on-error: true
- run: "if '${{ steps.execute_action.outcome }}' NEQ 'failure' exit 1\n"
  shell: "cmd"
```
