### ISSUE TITLE
Nested custom objects aren't supported for custom arguments

### ISSUE THREAD

**Issue by Vampire** [krzema12/github-actions-kotlin-dsl#298]
To overcome the limits of built-in matrices (#297), I tried to use `_customArguments` as usual.
Unfortunately it is also way too limited for that use-case currently.
What I need to model is

```yml
strategy:
    fail-fast: false
    matrix:
        "environment":
            - "windows-2019"
            - "windows-2022"
            - "windows-latest"
        "distribution":
            - "wsl-id": "Debian"
              "user-id": "Debian"
              "match-pattern": "*Debian*"
              "default-absent-tool": "dos2unix"
            - "wsl-id": "Alpine"
              "user-id": "Alpine"
              "match-pattern": "*Alpine*"
              "default-absent-tool": "dos2unix"
            - "wsl-id": "kali-linux"
              "user-id": "kali-linux"
              "match-pattern": "*Kali*"
              "default-absent-tool": "dos2unix"
            - "wsl-id": "openSUSE-Leap-15.2"
              "user-id": "openSUSE-Leap-15.2"
              "match-pattern": "*openSUSE*Leap*15.2*"
              "default-absent-tool": "which"
            - "wsl-id": "Ubuntu"
              "user-id": "Ubuntu-20.04"
              "match-pattern": "*Ubuntu*20.04*"
              "default-absent-tool": "dos2unix"
            - "wsl-id": "Ubuntu-18.04"
              "user-id": "Ubuntu-18.04"
              "match-pattern": "*Ubuntu*18.04*"
              "default-absent-tool": "dos2unix"
            - "wsl-id": "Ubuntu-16.04"
              "user-id": "Ubuntu-16.04"
              "match-pattern": "*Ubuntu*16.04*"
              "default-absent-tool": "dos2unix"
        "distribution2":
            - "wsl-id": "Debian"
              "user-id": "Debian"
              "match-pattern": "*Debian*"
              "default-absent-tool": "dos2unix"
        "exclude":
            - "environment": "windows-2019"
              "distribution":
                  "wsl-id": "Debian"
                  "user-id": "Debian"
                  "match-pattern": "*Debian*"
                  "default-absent-tool": "dos2unix"
              "distribution2":
                  "wsl-id": "Debian"
                  "user-id": "Debian"
                  "match-pattern": "*Debian*"
                  "default-absent-tool": "dos2unix"
            - "environment": "windows-2022"
              "distribution":
                  "wsl-id": "Debian"
                  "user-id": "Debian"
                  "match-pattern": "*Debian*"
                  "default-absent-tool": "dos2unix"
              "distribution2":
                  "wsl-id": "Debian"
                  "user-id": "Debian"
                  "match-pattern": "*Debian*"
                  "default-absent-tool": "dos2unix"
            - "environment": "windows-latest"
              "distribution":
                  "wsl-id": "Debian"
                  "user-id": "Debian"
                  "match-pattern": "*Debian*"
                  "default-absent-tool": "dos2unix"
              "distribution2":
                  "wsl-id": "Debian"
                  "user-id": "Debian"
                  "match-pattern": "*Debian*"
                  "default-absent-tool": "dos2unix"
        "include":
            - "environment": "windows-2019"
              "distribution":
                  "wsl-id": "Debian"
                  "user-id": "Debian"
                  "match-pattern": "*Debian*"
                  "default-absent-tool": "dos2unix"
              "distribution2":
                  "wsl-id": "Ubuntu"
                  "user-id": "Ubuntu-20.04"
                  "match-pattern": "*Ubuntu*20.04*"
                  "default-absent-tool": "dos2unix"
            - "environment": "windows-2022"
              "distribution":
                  "wsl-id": "Debian"
                  "user-id": "Debian"
                  "match-pattern": "*Debian*"
                  "default-absent-tool": "dos2unix"
              "distribution2":
                  "wsl-id": "Ubuntu"
                  "user-id": "Ubuntu-20.04"
                  "match-pattern": "*Ubuntu*20.04*"
                  "default-absent-tool": "dos2unix"
            - "environment": "windows-latest"
              "distribution":
                  "wsl-id": "Debian"
                  "user-id": "Debian"
                  "match-pattern": "*Debian*"
                  "default-absent-tool": "dos2unix"
              "distribution2":
                  "wsl-id": "Ubuntu"
                  "user-id": "Ubuntu-20.04"
                  "match-pattern": "*Ubuntu*20.04*"
                  "default-absent-tool": "dos2unix"
```
but with `_customArguments` I just achieved
```yml
strategy:
    fail-fast: false
    matrix: :-(
```
as it does not support deeper nested structures.

**Comment by Vampire** [comment]
Also `null` should be modelable, to for example model this:
```yaml
strategy:
    fail-fast: false
    matrix:
        environment:
            - windows-2019
            - windows-2022
            - windows-latest
        distribution:
            - id: invalid
              label: invalid
            - id: ''
              label: ''
            - id: null
              label: 'null'
```
