### ISSUE TITLE
[Core feature request] Defaults Parameters

### ISSUE THREAD

**Issue by scottbisaillon** [krzema12/github-actions-kotlin-dsl#347]
**What feature do you need?**
[`defaults`](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#defaults) parameter for workflows and jobs.

**Do you have an example usage?**
```ymal
defaults:
  run:
    shell: bash
    working-directory: scripts
```

**Is there a workaround for not having this feature? If yes, please describe it.**
The custom arguments for either workflows or jobs do not work in this case since its a nested map and custom arguments only support one level of nesting at the moment.

**Comment by krzema12** [comment]
> **Is there a workaround for not having this feature? If yes, please describe it.** The custom arguments for either workflows or jobs do not work in this case since its a nested map and custom arguments only support one level of nesting at the moment.

FTR, this issue is tracked as #298.

**Comment by krzema12** [comment]
I'm actually wondering if we should implement this feature. Kotlin also has a notion of defaults, I can imagine creating a helper function with appropriate default parameters that could then be called, and it would be type-safe:

```kotlin
fun WorkflowBuilder.myJob(
    id: String,
    name: String? = null,
    block: JobBuilder.() -> Unit,
): Job {
    return job(
        id = id,
        name = name,
        runsOn = UbuntuLatest,
        env = linkedMapOf("SOME_VARIABLE" to "some-value"),
        timeoutMinutes = 123,
    ) {
        block()
    }
}

// and then use it like this

workflow(...) {
    myJob(
        id = "build_docs",
        name = "Build docs",
    ) {
        uses(CheckoutV3())
        uses(SetupPythonV4(pythonVersion = "3.8"))
        run("pip install -r docs/requirements.txt")
        run("mkdocs build --site-dir public")
    }
}
```

It wouldn't produce exactly the same YAML as with native support for default parameters, but the effect would be the same. Actually, it would even add to the YAML being explicit - each job would have all default parameters enumerated where they are used, we wouldn't have to traverse up to see which values are used.
 
Would it address your needs @scottbisaillon?

**Comment by scottbisaillon** [comment]
Would this flatten the default paramter map to top level parameters on the workflow and job builders? 

I'm not opposed to this solution, moreso just trying to visualize how it would look if there are more nested maps/parameters added to defaults. I think right now it only has the one `run` map with it's two parameters, but could see more being added to the action spec in the future.

Also how would the default parameters be associated with a section, explicit variable names like `runShell` or something to that effect?

**Comment by krzema12** [comment]
> Would this flatten the default paramter map to top level parameters on the workflow and job builders?
> 
> I'm not opposed to this solution, moreso just trying to visualize how it would look if there are more nested maps/parameters added to defaults. I think right now it only has the one `run` map with it's two parameters, but could see more being added to the action spec in the future.

Sorry, I don't quite get it. The idea is to actually ignore GitHub's `defaults` feature, and achieve something similar using Kotlin's mechanisms. Could you give some example where it won't work or will cause troubles, especially regarding the flattening you mentioned?

> Also how would the default parameters be associated with a section, explicit variable names like `runShell` or something to that effect?

What do you mean by a section? If I correctly understand your question: my idea was to prepare a single Kotlin function (like `myJob` in the example above) per set of defaults, and the function name could have a descriptive name what kind of defaults this function implements. Then, instead of calling the DSL's built-in functions, you would call these functions depending on your needs.

I'd appreciate some example snippets, then it should be easier to discuss stuff :smile:

**Comment by scottbisaillon** [comment]
I think a snippet would definitely make it easier so here is an example of a workflow structure I use quite a bit. Since my app is in a mono-repo with many sub packages included, setting the `working-directory` is done in every action to make the path references easier throughout.

```yaml
name: dashboard_repository

on:
  push:
    branches:
      - master
      - development
    paths:
      - "packages/dashboard_repository/**"
      - ".github/workflows/dashboard_repository.yaml"

  pull_request:
    paths:
      - "packages/dashboard_repository/**"
      - ".github/workflows/dashboard_repository.yaml"

jobs:
  build:
    defaults:
      run:
        working-directory: packages/dashboard_repository

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: 2.17.1

      - name: Install Tools
        run: ${GITHUB_WORKSPACE}/.github/workflows/scripts/install-tools-dart.sh

      - name: Install Dependencies
        run: dart pub get

      - name: Format
        run: dart format --set-exit-if-changed .

      - name: Analyze
        run: dart analyze --fatal-infos --fatal-warnings .

      - name: Run Tests
        run: dart run coverage:test_with_coverage

      - name: Check Code Coverage
        uses: VeryGoodOpenSource/very_good_coverage@v1.2.0
        with:
          min_coverage: 80
          path: packages/dashboard_repository/coverage/lcov.info
```

I am probably just misunderstanding your proposal, but I am not sure what it would look like to achieve this part of the job:

```yaml
jobs:
  build:
    defaults:
      run:
        working-directory: packages/dashboard_repository
```

In your example of the default function, would it look something like this with the `workingDirectory` parameter?

```kotlin
fun WorkflowBuilder.myJob(
    id: String,
    name: String? = null,
    workingDirectory: String? = null,
    block: JobBuilder.() -> Unit,
): Job {
    return job(
        id = id,
        name = name,
        runsOn = UbuntuLatest,
        env = linkedMapOf("SOME_VARIABLE" to "some-value"),
        timeoutMinutes = 123,
    ) {
        block()
    }
}
```

> What do you mean by a section?

As far as I understand, the `defaults` section is very specific in that in only supports a handful of values at the moment. Right now it only has the `run` section with two parameters, `working-directory` and `shell`. If another section was added, I could see this option becoming difficult to maintain, but I could just not be seeing something. 

I know that's quite a bit so feel free to only respond to bits. 😂

**Comment by krzema12** [comment]
Thanks for the example! Here's how it could be implemented:

```kotlin
workflow(
    name = "Test workflow",
    on = listOf(Push()),
    sourceFile = sourceTempFile.toPath()
) {
    job(
        id = "build",
        runsOn = RunnerType.UbuntuLatest
    ) {
        fun run(name: String, command: String) =
            run(
                name = name,
                command = command,
                _customArguments = mapOf(
                    // Adding a type-safe field tracked in https://github.com/krzema12/github-actions-kotlin-dsl/issues/360
                    "working-directory" to StringCustomValue("packages/dashboard_repository"),
                )
        )

        uses(CheckoutV3())

        run(
            name = "Install Dependencies",
            command = "dart pub get"
        )

        run(
            name = "Format",
            command = "dart format --set-exit-if-changed ."
        )

        run(
            name = "Analyze",
            command = "dart analyze --fatal-infos --fatal-warnings ."
        )

        // ...
    }
}
```

so you define a local `run` function that shadows the function coming from `JobBuilder`. Depending on your taste, you can also name this function meaningfully like `runInDashboardRepository`) and/or move its definition somewhere to a place where utils live, with slight modifications. It produces this YAML:

```yaml
# This file was generated using Kotlin DSL (.github/workflows/some_workflow.main.kts).
# If you want to modify the workflow, please change the Kotlin file and regenerate this YAML file.
# Generated with https://github.com/krzema12/github-actions-kotlin-dsl

name: Test workflow

on:
  push:

jobs:
  "build":
    runs-on: "ubuntu-latest"
    steps:
      - id: step-0
        uses: actions/checkout@v3
      - id: step-1
        name: Install Dependencies
        working-directory: packages/dashboard_repository
        run: dart pub get
      - id: step-2
        name: Format
        working-directory: packages/dashboard_repository
        run: dart format --set-exit-if-changed .
      - id: step-3
        name: Analyze
        working-directory: packages/dashboard_repository
        run: dart analyze --fatal-infos --fatal-warnings .
```

Would it be a good fit for your use case?

Regarding `defaults` being limited only to this handful of parameters: I didn't test it end-to-end, but having a quick glance at [these search results](https://github.com/search?l=&p=4&q=defaults++extension%3Ayaml+path%3A.github%2Fworkflows&ref=advsearch&type=Code) you may indeed be right only these ones are supported. The approach I've presented, though, isn't limited to these - you can set a "default" for any job/step parameter you wish.
