### ISSUE TITLE
[Core feature request] `env` on workflow, job and step level

### ISSUE THREAD

**Issue by NikkyAI** [krzema12/github-actions-kotlin-dsl#55]
**What feature do you need?**
_Please add a link to GitHub docs (https://docs.github.com/en/actions/using-workflows/) which describes the desired feature._
https://docs.github.com/en/actions/learn-github-actions/environment-variables

**Do you have an example usage?**
_Best if a YAML snippet is pasted here, or if your project is open-source, an URL to your workflow._

some tasks need to call scripts / binaries that expect some env variables

```yaml
- name: Send Webhook Notification
  if: always()
  env:
    JOB_STATUS: ${{ job.status }}
    WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
    HOOK_OS_NAME: ${{ runner.os }}
    WORKFLOW_NAME: ${{ github.workflow }}
  run: |
    git clone https://github.com/DiscordHooks/github-actions-discord-webhook.git webhook
    bash webhook/send.sh $JOB_STATUS $WEBHOOK_URL
  shell: bash
```
