### ISSUE TITLE
[Core feature request] Allow accessing step outputs

### ISSUE THREAD

**Issue by NikkyAI** [krzema12/github-actions-kotlin-dsl#56]
**What feature do you need?**
_Please add a link to GitHub docs (https://docs.github.com/en/actions/using-workflows/) which describes the desired feature._
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsid

**Do you have an example usage?**
_Best if a YAML snippet is pasted here, or if your project is open-source, an URL to your workflow._
```yaml
- name: Build and push
  id: docker_build
  uses: docker/build-push-action@v2
  with:
    context: ./
    file: ./Dockerfile
    push: true
    tags: ${{ secrets.DOCKER_HUB_USERNAME }}/discordbot:latest
- name: Image digest
  run: echo ${{ steps.docker_build.outputs.digest }}
```

even better would be if we could use it somewhat like so:

```kotlin

fun variable(variable: String): String = "\${{ $variable }}"

val dockerBuild = uses(
    name = "Build and push",
    id = "docker_build_push",
    action = DockerBuildPush(
        context = ".",
        file = "./Dockerfile",
        push = true,
        tags = "${variable("secrets.DOCKER_HUB_USERNAME")}/discordbot:latest",
    )
)
run(
    name = "image digest",
    command ="echo ${dockerBuild.outputsVariable("digest")}",
//      command = "echo ${variable("steps.${dockerBuild.id}.outputs.digest")}",
)
```

but just having access to the id field would let me build the command `echo ${{ steps.docker_build.outputs.digest }}` myself too
