### ISSUE TITLE
[Core feature request] condition on job

### ISSUE THREAD

**Issue by NikkyAI** [krzema12/github-actions-kotlin-dsl#57]
**What feature do you need?**
_Please add a link to GitHub docs (https://docs.github.com/en/actions/using-workflows/) which describes the desired feature._
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idif

**Do you have an example usage?**
_Best if a YAML snippet is pasted here, or if your project is open-source, an URL to your workflow._
```yaml

jobs:
  build:
   .....
  notify:
    name: Discord Notification
    runs-on: ubuntu-latest
    needs: # make sure the notification is sent AFTER the jobs you want included have completed
      - build
    if: ${{ always() }} # You always want to be notified: success, failure, or cancelled
    steps:
    - name: Notify
      uses: nobrayner/discord-webhook@v1
      with:
        github-token: ${{ github.token }}
        discord-webhook: ${{ secrets.WEBHOOK_URL }}
        include-details: true
```
