### ISSUE TITLE
[Bug] Incorrect YAML when value starts with `*`, `[` or `!`

### ISSUE THREAD

**Issue by krzema12** [krzema12/github-actions-kotlin-dsl#70]
# Action

```kotlin
            uses(
                name = "Publish JUnit report",
                action = object : Action("mikepenz", "action-junit-report", "v2") {
                    override fun toYamlArguments() = linkedMapOf(
                        "report_paths" to "**/build/reports/tests/**",
                    )
                },
                condition = "always()",
            )
```

# Expected

Working action.

# Actual

I got an error from GitHub Actions: 

> Invalid workflow file : .github/workflows/build.yaml#L40
> You have an error in your yaml syntax on line 40

It resulted in such YAML:
```
- name: Publish JUnit report
  uses: mikepenz/action-junit-report@v2
  with:
    report_paths: **/build/reports/tests/**
```

# Workaround

Add single quotes in the value:

```kotlin
"report_paths" to "'**/build/reports/tests/**'",
```

# Library version

v0.6.0
