### ISSUE TITLE
[Core feature request] Trigger is missing path & path-ignore

### ISSUE THREAD

**Issue by jmfayard** [krzema12/github-actions-kotlin-dsl#85]
**What feature do you need?**

[on.<push|pull_request|pull_request_target>.<paths|paths-ignore>](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onpushpull_requestpull_request_targetpathspaths-ignore)

**Do you have an example usage?**

```yaml
// https://github.com/jmfayard/refreshVersions/blob/5870e18a5ca8ad9ec8640b38eb7c37abc4dcf585/.github/workflows/build-mkdocs-website.yml#L2-L9
on:
  push:
    paths:
      - 'docs/**'
      - 'mkdocs.yml'
      - 'CHANGELOG.md'
```      

or

```
// https://github.com/jmfayard/refreshVersions/blob/5870e18a5ca8ad9ec8640b38eb7c37abc4dcf585/.github/workflows/check-build.yml

on:
  pull_request:
    paths:
      - 'plugins/**'
      - 'sample-kotlin/**'
  push:
    branches:
      - main
    paths-ignore:
      - 'plugins/**'
      - 'sample-kotlin/**'
      - 'sample-groovy/**'
      - '!**.md'
```
